language: node_js
sudo: required
node_js:
  - "8.11.4"

cache:
directories:
  - $HOME/.meteor

before_cache:
  - rm -f $HOME/.meteor/log/*.log

before_install:
  - docker pull olivierjm/spark
  - docker run -d -e ROOT_URL=127.0.0.1:80:4567 -p 80:3000 olivierjm/spark

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

branches:
only:
  - master

script:
  - npm run lint
